CREATE TABLE IF NOT EXISTS _etudiants (id VARCHAR(100) PRIMARY KEY NOT NULL, nom VARCHAR(100), prenom VARCHAR(100), age VARCHAR(2));
CREATE TABLE IF NOT EXISTS _cours (id VARCHAR(100) PRIMARY KEY NOT NULL, nom VARCHAR(100), annee VARCHAR(4));
CREATE TABLE IF NOT EXISTS _notes (id INT PRIMARY KEY NOT NULL AUTO_INCREMENT, note VARCHAR(100), cours_id VARCHAR(100), etudiant_id VARCHAR(100));
AlTER TABLE _notes ADD CONSTRAINT FK_etudiant FOREIGN KEY (etudiant_id) REFERENCES _etudiants(id);
AlTER TABLE _notes ADD CONSTRAINT FK_cours FOREIGN KEY (cours_id) REFERENCES _cours(id);